# Name of the workflow
name : Docker Images building and pushing to Docker Hub.

# Can be triggered manually or by a push event
on : [workflow_dispatch, push]

# Jobs in the workflow
jobs :
  # Job to build docker images and pushithem to Docker Hub
  docker-image:
    # Runs on the latest version of ubuntu
    runs-on: ubuntu-latest
    # Steps involved in the job
    steps:
      - name: Getting the code
        uses: actions/checkout@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DockerHub_Username }}
          password: ${{ secrets.DockerHub_Password }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            sunilgv/sample-html:latest
            sunilgv/sample-html:${{ github.run_number }}